### ISSUE TITLE
[android] NoSuchMethodError: android.media.RemoteControlClient$MetadataEditor.putObject

### ISSUE THREAD

**Issue by kesha-antonov** [tanguyantoine/react-native-music-control#113]
Hello! I have crashes in production. Could not reproduce locally.

Here's the log:

```
Could not invoke MusicControlManager.setNowPlaying

java.lang.NoSuchMethodError: android.media.RemoteControlClient$MetadataEditor.putObject
    at android.support.v4.media.session.MediaSessionCompatApi19.addNewMetadata(MediaSessionCompatApi19.java:80)
    at android.support.v4.media.session.MediaSessionCompatApi19.setMetadata(MediaSessionCompatApi19.java:50)
    at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1729)
    at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setActive(MediaSessionCompat.java:1649)
    at android.support.v4.media.session.MediaSessionCompat.setActive(MediaSessionCompat.java:408)
    at com.tanguyantoine.react.MusicControlModule.setNowPlaying(MusicControlModule.java:251)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:193)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:841)
java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:193)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:841)
java.lang.RuntimeException: Could not invoke MusicControlManager.setNowPlaying
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:385)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:193)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:841)
```

# Description

1. Sample code (provide repo url or sample code)

2. Platform ?
   - [ ] iOS
   - [x ] Android
   
   
3. Device
  - [ ] Simulator
  - [ x] Real device

**Please give some hints how to fix it.**

**Comment by Guichaguri** [comment]
I believe this is a issue with the support library. You can update it to a new version in your app.

**Comment by kesha-antonov** [comment]
@Guichaguri Thanks! I will try that.

**Comment by kesha-antonov** [comment]
I see that we use
```android.support.v7.app.NotificationCompat```which was deprecated in API 26 https://developer.android.com/reference/android/support/v7/app/NotificationCompat.Builder.html

https://github.com/tanguyantoine/react-native-music-control/blob/master/android/src/main/java/com/tanguyantoine/react/MusicControlModule.java#L19

**Comment by kesha-antonov** [comment]
Which of ```com.android.support:appcompat-v7``` versions do you use in production? @Guichaguri

**Comment by kesha-antonov** [comment]
I'll leave ```compile "com.android.support:appcompat-v7:25.4.0"``` for now and see how it goes

**Comment by kesha-antonov** [comment]
Still same error:
```
java.lang.NoSuchMethodError: android.media.RemoteControlClient$MetadataEditor.putObject
    at android.support.v4.media.session.MediaSessionCompatApi19.addNewMetadata(MediaSessionCompatApi19.java:80)
    at android.support.v4.media.session.MediaSessionCompatApi19.setMetadata(MediaSessionCompatApi19.java:50)
    at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1849)
    at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setActive(MediaSessionCompat.java:1769)
    at android.support.v4.media.session.MediaSessionCompat.setActive(MediaSessionCompat.java:437)
    at com.tanguyantoine.react.MusicControlModule.setNowPlaying(MusicControlModule.java:251)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:157)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:864)
java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:157)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:864)
java.lang.RuntimeException: Could not invoke MusicControlManager.setNowPlaying
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:385)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:157)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:864)
```

**Comment by Guichaguri** [comment]
> Which of com.android.support:appcompat-v7 versions do you use in production? @Guichaguri

I'm not using this module in production anymore. I'm using [react-native-track-player](https://github.com/react-native-kit/react-native-track-player) instead.

> Still same error

I'll take a look when I have time.

**Comment by kesha-antonov** [comment]
Thank you! @Guichaguri

**Comment by marf** [comment]
Same problem, you can't use this package with for example react-native-fbsdk since they use different versions of the com.android.support:appcompat-v7 and in particular this package uses an older (and deprecated) version of it while react-native-fbsdk uses a new version which you can't downgrade.

**Comment by rborn** [comment]
@kesha-antonov @marf did you find a fix ? I have this on a few devices with android 6 and 5 ( production, reported by crashlytics) 🤗

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?

**Comment by tanguyantoine** [comment]
closing (stale)
