### ISSUE TITLE
Switching setNowPlaying really fast crashes app

### ISSUE THREAD

**Issue by deafkittten** [tanguyantoine/react-native-music-control#121]
# Description
I have an app with two players and they set setNowPlaying when switching between them. If I change view really fast the app crashes. I tried setting resetNowPlaying first but it seems like the artwork thread get's decoupled somehow and confuses everything anyway.

1. Sample code (provide repo url or sample code)
Nothing special.

2. Platform ?
   - [ ] iOS
   - [X] Android
   
   
3. Device
  - [X] Simulator
  - [X] Real device

**Comment by Guichaguri** [comment]
Crash logs?

**Comment by deafkittten** [comment]
`Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192
       at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:818)
       at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:793)
       at com.android.okhttp.okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:57)
       at com.android.okhttp.internal.http.Http1xStream.writeRequest(Http1xStream.java:167)
       at com.android.okhttp.internal.http.Http1xStream.writeRequestHeaders(Http1xStream.java:123)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:593)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:482)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:249)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source)
       at com.tanguyantoine.react.MusicControlModule.loadArtwork(MusicControlModule.java:421)
       at com.tanguyantoine.react.MusicControlModule.access$000(MusicControlModule.java:35)
       at com.tanguyantoine.react.MusicControlModule$1.run(MusicControlModule.java:239)
       at java.lang.Thread.run(Thread.java:764)`

**Comment by tanguyantoine** [comment]
still crashing?

**Comment by arondn2** [comment]
Hi, guys.

I had the same issue and I resolved it adding the permission `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` in the AndroidManifest.xml.

Regards.

**Comment by tanguyantoine** [comment]
@arondn2 would you mind creating a pull request to update the README? :-) 🙏

**Comment by arondn2** [comment]
@tanguyantoine sure. I'll work on that
