### ISSUE TITLE
Crashing on Android 8.0+: Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent

### ISSUE THREAD

**Issue by jeffmon** [tanguyantoine/react-native-music-control#191]
# Description
Getting crash reports from Firebase Crashlytics:
```
Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.truthforlife.app/com.tanguyantoine.react.MusicControlNotification$NotificationService }: app is in background uid UidRecord{ddc63fd u0a88 CAC  bg:+45m52s470ms idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
       at android.app.ContextImpl.startService(ContextImpl.java:1484)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at com.tanguyantoine.react.MusicControlModule.init(MusicControlModule.java:150)
       at com.tanguyantoine.react.MusicControlModule.updatePlayback(MusicControlModule.java:291)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```

More specifically with `MusicControlModule.java line 150`

This might be a possible solution? https://stackoverflow.com/questions/49961273/java-lang-illegalstateexception-not-allowed-to-start-service-intent-while-try  

1. Sample code (provide repo url or sample code)
N/A

2. Platform ?
   - [ ] iOS
   - [x] Android
   
   
3. Device
  - [ ] Simulator
  - [x] Real device

**Comment by marf** [comment]
Same problem here

**Comment by tanguyantoine** [comment]
What android version are you using?

**Comment by marf** [comment]
From Android 8.0+ it gives this error since you have to use startForegroundService and not startService and also display a notification of the fact that the up is running a service.

I have made a fix in my repo: https://github.com/marf/react-native-music-control/

In function init of MusicControlModule.java:

```
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O){
            context.startForegroundService(myIntent);

        }
        else
            context.startService(myIntent);
```

In MusicControlNotification.java (NotificationService):

```
 @Override
        public void onCreate() {
            super.onCreate();

            if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                /*Notification notification = new Notification.Builder(MusicControlModule.INSTANCE.context, MusicControlModule.INSTANCE.CHANNEL_ID)
                        .build();*/
                Notification notification = MusicControlModule.INSTANCE.notification.prepareNotification(MusicControlModule.INSTANCE.nb,false);
                startForeground(NOTIFICATION_ID, notification);
            }
        }

```

Also in MusicControlNotification.java I created a new function and changed the show function:

```
public Notification prepareNotification(NotificationCompat.Builder builder, boolean isPlaying) {
        // Add the buttons
        builder.mActions.clear();
        if(previous != null) builder.addAction(previous);
        if(skipBackward != null) builder.addAction(skipBackward);
        if(play != null && !isPlaying) builder.addAction(play);
        if(pause != null && isPlaying) builder.addAction(pause);
        if(stop != null) builder.addAction(stop);
        if(next != null) builder.addAction(next);
        if(skipForward != null) builder.addAction(skipForward);

        // Set whether notification can be closed based on closeNotification control (default PAUSED)
        if(module.notificationClose == MusicControlModule.NotificationClose.ALWAYS) {
            builder.setOngoing(false);
        } else if(module.notificationClose == MusicControlModule.NotificationClose.PAUSED) {
            builder.setOngoing(isPlaying);
        } else { // NotificationClose.NEVER
            builder.setOngoing(true);
        }

        builder.setSmallIcon(customIcon != 0 ? customIcon : smallIcon);

        // Open the app when the notification is clicked
        String packageName = context.getPackageName();
        Intent openApp = context.getPackageManager().getLaunchIntentForPackage(packageName);
        builder.setContentIntent(PendingIntent.getActivity(context, 0, openApp, 0));

        // Remove notification
        Intent remove = new Intent(REMOVE_NOTIFICATION);
        remove.putExtra(PACKAGE_NAME, context.getApplicationInfo().packageName);
        builder.setDeleteIntent(PendingIntent.getBroadcast(context, 0, remove, PendingIntent.FLAG_UPDATE_CURRENT));

        return builder.build();
    }

    public synchronized void show(NotificationCompat.Builder builder, boolean isPlaying) {
        NotificationManagerCompat.from(context).notify(NOTIFICATION_ID, prepareNotification(builder, isPlaying));
    }
```

With these changes the controls appear when you open the app and you can use the new API which uses startForegroundService and avoid the errors.

**Comment by moonstruck** [comment]
@marf You may fork the repo and send a pull request.

**Comment by marf** [comment]
@moonstruck I don't know if this is the best solution

**Comment by tanguyantoine** [comment]
thank you marf, I'll publish it as soon as it is merged 👍

**Comment by marf** [comment]
I have cleaned up the code, I think you can merge
