### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tanguyantoine.react.MusicControlAudioFocusListener.requestAudioFocus()' on a null object reference

### ISSUE THREAD

**Issue by brave-merida** [tanguyantoine/react-native-music-control#268]
# Description
I have upgraded the react-native version to 0.59.8 and react-native-music-control version to 0.10.4
iOS app works fine, but android getting this error.
```
E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tanguyantoine.react.MusicControlAudioFocusListener.requestAudioFocus()' on a null object reference
        at com.tanguyantoine.react.MusicControlModule.observeAudioInterruptions(MusicControlModule.java:223)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:761)
```

1. Environment
react-native: 0.59.8
react-native-music-control: 0.10.4

2. Platform ?

   - [ ] iOS
   - [x] Android
   
3. Device
  - [x] Simulator
  - [x] Real device

Please help me, thanks.

**Comment by mohsinriaz17** [comment]
remove MusicControl.handleAudioInterruptions(true) for Android
had the same issue

**Comment by tanguyantoine** [comment]
Is it solved or is it a workaround?

**Comment by jeanffc** [comment]
Isn't working yet for me :/

![Screenshot_1571263144](https://user-images.githubusercontent.com/767813/66962324-19efc900-f047-11e9-9020-4a92ff3e5131.png)

**Comment by pedro-lb** [comment]
> remove MusicControl.handleAudioInterruptions(true) for Android
> had the same issue

Works for us here! Thanks, @mohsinriaz17 <3
