### ISSUE TITLE
Exception Bad notification posted from package

### ISSUE THREAD

**Issue by dnish** [tanguyantoine/react-native-music-control#69]
Hey,
we getting the following exception message from Bugsnag:

```
android.app.RemoteServiceException Bad notification posted from package com.xx.android: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.xx.android user=UserHandle{0} id=0 tag=MusicControl score=0 key=0|com.xx.android|0|MusicControl|10092: Notification(pri=0 contentView=com.xx.android/0x109007f vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 category=transport actions=3 vis=PRIVATE)) 
    ActivityThread.java:1534 android.app.ActivityThread$H.handleMessage
    Handler.java:102 android.os.Handler.dispatchMessage
    Looper.java:135 android.os.Looper.loop
    ActivityThread.java:5538 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    Method.java:372 java.lang.reflect.Method.invoke
    ZygoteInit.java:960 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:755 com.android.internal.os.ZygoteInit.main
```

Platform ?
   - [ ] iOS
   - [x] Android
   
   
 Device
  - [ ] Simulator
  - [x] Real device (Android 5.0)

It seems only to happen on Android versions below 6.0.

**Comment by skleest** [comment]
Seeing the same error as well!

**Comment by tanguyantoine** [comment]
same as #70

**Comment by Guichaguri** [comment]
This seems to be a bug with the support library. It should handle the notification controls on versions below 6.0. Can you refresh the dependencies and try again?

**Comment by Guichaguri** [comment]
I'll be closing this issue for inactivity. Feel free to reopen it if the problem persists.

**Comment by hudashot** [comment]
I am seeing the same message with a fresh build from `master`:

```
FATAL EXCEPTION: main
Process: com.mycoolapp, PID: 21881
android.app.RemoteServiceException: Bad notification posted from package com.mycoolapp: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.mycoolapp user=UserHandle{0} id=0 tag=MusicControl score=0 key=0|com.mycoolapp|0|MusicControl|10102: Notification(pri=0 contentView=com.mycoolapp/0x109007f vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 category=transport vis=PRIVATE))
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

@Guichaguri, could you please clarify which support library are you referring to?
